### ISSUE TITLE
[EPIC] Github User Interface

### ISSUE THREAD

**Issue by KevFan** [Kuadrant/kuadra#31]
# WHAT

Introduce functionality to interface with Github API in order to add the github user to Orgs / teams etc

The User CR interface might be:
```yaml
kind: User
metadata:
  - name: kuadra-user
spec:
  awsAccount:
...
...
  github:
    spec:
      organizations:
        - name: kuadrant
          teams:
            - engineering
```

Things that might be required might include:

- [x] Introduce a GithubUser CR & Controller similiar to [AWSAccount](https://github.com/Kuadrant/kuadra/blob/main/api/v1/awsaccount_types.go#L27) 
- [ ] Update the [Kuadra User ](https://github.com/Kuadrant/kuadra/blob/main/api/v1/user_types.go#L24-L27) CR to include Github User information and create the Github User CR similar to how it's done for[ AWSAccount](https://github.com/Kuadrant/kuadra/blob/main/internal/controller/user_controller.go#L88-L100)
- [ ] Update the GithubUser reconcile to interface with [Github API](https://docs.github.com/en/rest?apiVersion=2022-11-28) using [Github Client](https://github.com/google/go-github) in order to add the Github User to the specific org / teams 
- [ ] Add integration tests
