### ISSUE TITLE
[EPIC] CI/CD

### ISSUE THREAD

**Issue by KevFan** [Kuadrant/kuadra#35]
The CI/CD github workflows at the moment only runs the tests on PRs. 

This can be improved to include things such as:
- [ ] Checking for format of code and imports via `gofmt` and `goimports`
- [ ] Introduce linting such as `golangci` to detect common linting issues
- [ ] Introduce a github action for detecting typos 
- [ ] Test code coverage
- [ ] Auto adding issues into Kuadra project board
